# Site
repository: eshaan7/resume
favicon: assets/glider.ico

# Personal info
name: Eshaan Bansal
title: GSoC'20 | Pentester | Fullstack Developer | CTF player | Sophomore at USICT
email: eshaan7bansal@gmail.com
resume: https://drive.google.com/file/d/1BLJXR_rFFLP7wobE-Fog363JcbH5uttQ/view
website: https://eshaan7.github.io/
blog: http://eshaan7.github.io/blog/post/

# Social links
twitter_username: mask0fmydisguis
github_username: eshaan7
# medium_username: eshaan7
instagram_username: maskofmydisguise
linkedin_username: eshaan7
# youtube_username: jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a sophomore pursuing B.Tech in IT at <a href="http://ipu.ac.in/usict" target="_blank">USICT</a>, GGSIP University Main Campus. 

  My CS interests currently lie in <mark>Cybersecurity</mark> and <mark>Web Development</mark>.

  What I am working on right now:
  - GSoC'20 student developer for <a href="https://github.com/certego/IntelOwl" target="_blank">IntelOwl</a> 
  under <a href="https://www.honeynet.org/" target="_blank" >The Honeynet Project</a>
  - Practicing on <a href="https://www.hackthebox.eu/profile/256874" target="_blank">HackTheBox.eu</a>.

  I am looking for cybersecurity, software development or research internships for winter 2020. I am available remotely too.

  _A pdf version of my resume is available <a href="https://drive.google.com/file/d/1BLJXR_rFFLP7wobE-Fog363JcbH5uttQ/view" target="_blank" >here</a>._

# The most interesting things happening in my life, right now, academically speaking are:

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Achievements Section
achievements_title: "Few things I am proud of"

# Volunteering Experience section
volunteering_experience_title: "Infosec Community"

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love learning new things, and **blogs** are my way of doing so. I am an avid reader. 
  
  I am an absolute nerd and have worked on various technologies including Linux, Git, Heroku, Docker, Google Cloud Platform, Raspberry Pi and Arduino microcontroller.

  Alongside my interests in cybersecurity and web development some of my other interests and hobbies are:
  - Food, lots of it.
  - TV Shows
  - Blockchain and Cryptocurrencies

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
#  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
